name: hello ops girls prod pipeline
run-name: prod-ci
on:
  workflow_run:
    workflows: ["hello ops girls dev pipeline"]
    branches: [main]
    types:
      - completed
  push:
    branches: [workshop-part3]

env:
  AWS_ACCOUNT: "494526681395"
  AWS_REGION: "ap-southeast-1"

permissions:
  id-token: write
  contents: read


jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: aws-auth
        uses: "./.github/actions/aws-auth"
      - name: tag and push prod image to ECR
        env:
          REGISTRY: ${{ steps.aws-auth.outputs.registry }}
          REPOSITORY: devopsgirl2023/hello-ops-girl
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG 
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:latest
  deploy:
    runs-on: ubuntu-latest
    env:
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
      DOMAIN_NAME: ${{ github.event.repository.name }}.${{ secrets.DOMAIN_NAME }}
      STACK_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - id: aws-auth
        uses: "./.github/actions/aws-auth"
      - name: apply cloudformation stack
        run: |
          if ! aws cloudformation describe-stacks --stack-name ${STACK_NAME}; then
            aws cloudformation create-stack --stack-name ${STACK_NAME} --template-body file://cloudformation/stack.yaml --parameters ParameterKey=SecurityGroupName,ParameterValue=devops-girls-2023 ParameterKey=KeyName,ParameterValue=devops-girls-2023 ParameterKey=HostedZoneId,ParameterValue=${HOSTED_ZONE_ID} ParameterKey=DomainName,ParameterValue=${DOMAIN_NAME}
          else
            aws cloudformation update-stack --stack-name ${STACK_NAME} --template-body file://cloudformation/stack.yaml --parameters ParameterKey=SecurityGroupName,ParameterValue=devops-girls-2023 ParameterKey=KeyName,ParameterValue=devops-girls-2023 ParameterKey=HostedZoneId,ParameterValue=${HOSTED_ZONE_ID} ParameterKey=DomainName,ParameterValue=${DOMAIN_NAME}
          fi
      - name: deploy application container
        run: "true"
